# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-19 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='user',
        ),
    ]
